### ISSUE TITLE
Software: SimBit! A flexible, high performance forward-in-time population genetics simulation platform

### ISSUE THREAD

**Issue by RemiMattheyDoret** [2017-iEvoBio/organization#31]
If you are submitting information for a Birds of a Feather (BoF) topic, lightning talk, or entry 
to the Software Bazaar, please use the relevant template lines below. 

Software Bazaar: SimBit

**Authors:** Remi Matthey-Doret, Michael Whitlock
**Source code:** https://github.com/RemiMattheyDoret/SimBit
**License:** MIT License
**Abstract:** SimBit is a high performance forward-in-time population genetics simulation platform coded in C++. With SimBit, you can simulate complex demography, plasticity, epistasis, QTL and other things. The main secrets of SimBit relies into the use of bitwise operators and the fact that all memory allocation at the beginning of the simulation. SimBit has very good error handling to ensure a user understand what was unclear about its input.

**Comment by k8hertweck** [comment]
Thank you for your submission to the Software Bazaar! We've included you on the [list of presenters](https://github.com/2017-iEvoBio/organization/blob/master/bazaar.md) for June 24, 6-8 pm (same time and place as first Evolution poster session). There will be tables, power sources, and signs available. Please let us know if you have any questions!
